// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr6MZDoTPIvcIw47R4cwkgJhffWdfUXYQ',
    appId: '1:43016515624:web:fe48a5c21c2252e1bfc51d',
    messagingSenderId: '43016515624',
    projectId: 'myapp-92a2f',
    authDomain: 'myapp-92a2f.firebaseapp.com',
    storageBucket: 'myapp-92a2f.firebasestorage.app',
    measurementId: 'G-4H44GMJ4CB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-FQi7pdiYCfpTAPqIXGCQ0IvnsAWMziM',
    appId: '1:43016515624:android:0551d5c63e8b340bbfc51d',
    messagingSenderId: '43016515624',
    projectId: 'myapp-92a2f',
    storageBucket: 'myapp-92a2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLRz4hZ9lpp5jmWW6hGkQxExR8jyIgIDQ',
    appId: '1:43016515624:ios:a91bbd60f4ce51d3bfc51d',
    messagingSenderId: '43016515624',
    projectId: 'myapp-92a2f',
    storageBucket: 'myapp-92a2f.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );
}
